import type { ThemeSpellLabels } from "./theme-types.ts";

export const HOUSE_SPELL_LABELS: ThemeSpellLabels = {
  composerTitle: "Room of Requirement",
  timelineTitle: "Pensieve",
  themePickerTitle: "Sorting Hat",
  statusStreaming: "Legilimency",
  statusToolRunning: "Running tool",
  statusInterrupted: "Interrupted",
  statusError: "Howler",
  statusIdle: "Idle",
  statusReady: "Done",
  hintEnter: "Cast Spell",
  hintInterrupt: "Reducto",
  commandExit: "Mischief Managed",
  commandHelp: "Lumos",
  commandClear: "Obliviate",
  commandCompact: "Reducio",
  commandLog: "Specialis Revelio",
  commandTrace: "Appare Vestigium",
  commandTheme: "Sorting Hat",
  userInputLabel: "Prior Incantato",
  assistantStreamLabel: "Revelio",
  modeSwitchLabel: "Transfiguration",
};

export const ORIGIN_SPELL_LABELS: ThemeSpellLabels = {
  composerTitle: "Composer",
  timelineTitle: "Timeline",
  themePickerTitle: "Theme Picker",
  statusStreaming: "Thinking",
  statusToolRunning: "Running tool",
  statusInterrupted: "Interrupted",
  statusError: "Needs attention",
  statusIdle: "Idle",
  statusReady: "Done",
  hintEnter: "Enter send",
  hintInterrupt: "Ctrl+C interrupt",
  commandExit: "Exit",
  commandHelp: "Help",
  commandClear: "Clear",
  commandCompact: "Compact",
  commandLog: "Log",
  commandTrace: "Trace",
  commandTheme: "Theme",
  userInputLabel: "Submitted Input",
  assistantStreamLabel: "Assistant",
  modeSwitchLabel: "Mode",
};
